In [4]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import metrics

In [6]:
data=pd.read_csv('spam.csv')
data.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
x=data.iloc[:,[-1,1]].values
y=data.iloc[:,0].values
print(x)
print(y)

[['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'
  'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...']
 ['Ok lar... Joking wif u oni...' 'Ok lar... Joking wif u oni...']
 ["Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"
  "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"]
 ...
 ['Pity, * was in mood for that. So...any other suggestions?'
  'Pity, * was in mood for that. So...any other suggestions?']
 ["The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free"
  "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us

In [8]:
le=LabelEncoder()
x[:,1]=le.fit_transform(x[:,1])
x[:,0]=le.fit_transform(x[:,0])
y=le.fit_transform(y)
print(x)
print(y)

[[1080 1080]
 [3126 3126]
 [999 999]
 ...
 [3313 3313]
 [3932 3932]
 [3437 3437]]
[0 0 1 ... 0 0 0]


In [9]:
classifier=DecisionTreeClassifier(criterion="gini")
classifier.fit(x,y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [10]:
a=int(input("Enter the email: "))
b=int(input("Enter the email again: "))

Enter the email: 999
Enter the email again: 999


In [11]:
sc=StandardScaler()
t1=sc.fit_transform([[a,b]])
pt1=classifier.predict(t1)
pt1

array([1])